server:
  port: 9899
  servlet:
    context-path: /hotel-owner

app:
  storage:
    root: public
    upload:
      user: upload/user
      hotel: upload/hotel
      document: upload/document
      icon: upload/icons
    download:
      user: user

spring:
  web:
    resources:
      static-locations: file:${app.storage.root}/
  datasource:
    url: jdbc:mysql://103.161.172.90:3308/hotel_manager
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        integrator_provider: com.hotel.webapp.config.CustomSchemaIntegrator
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  signerKey: "1miFxX59tPM31zfyscZTV1ovDPI+2RI6f7nxOPe0/9Cnblzms/A3CY9Jid7QyEa0"
  valid-duration: 86400 # seconds -> 1 day
  refreshable-duration: 604800 # seconds -> 7 days
